### ISSUE TITLE
Running prospector on requirements.txt results in TypeError: unorderable types: str() > NoneType()

### ISSUE THREAD

**Issue by svenstaro** [landscapeio/prospector#59] opened 2014-10-29 00:15 UTC
I get `TypeError: unorderable types: str() > NoneType()` upon running prospector on requirements.txt. This is python 3.4 with prospector 0.7.

My requirements.txt: https://gist.github.com/374113a40502b04c5112

**Comment by carlio** [comment] 2015-02-06 07:54
Closing as cannot reproduce.

**Comment by erlingbo** [comment] 2015-03-21 12:40
```
Traceback (most recent call last):
  File "/home/erlingbo/.virtualenvs/mathjornet/bin/prospector", line 9, in <module>
    load_entry_point('prospector==0.9.9', 'console_scripts', 'prospector')()
  File "/home/erlingbo/.virtualenvs/mathjornet/lib/python3.4/site-packages/prospector/run.py", line 127, in main
    config = ProspectorConfig()
  File "/home/erlingbo/.virtualenvs/mathjornet/lib/python3.4/site-packages/prospector/config/__init__.py", line 33, in __init__
    self.libraries = self._find_used_libraries(self.config, self.profile)
  File "/home/erlingbo/.virtualenvs/mathjornet/lib/python3.4/site-packages/prospector/config/__init__.py", line 153, in _find_used_libraries
    map(libraries.append, autodetect_libraries(self.workdir))
  File "/home/erlingbo/.virtualenvs/mathjornet/lib/python3.4/site-packages/prospector/autodetect.py", line 136, in autodetect_libraries
    libraries = find_from_requirements(path)
  File "/home/erlingbo/.virtualenvs/mathjornet/lib/python3.4/site-packages/prospector/autodetect.py", line 117, in find_from_requirements
    reqs = find_requirements(path)
  File "/home/erlingbo/.virtualenvs/mathjornet/lib/python3.4/site-packages/requirements_detector/detect.py", line 114, in find_requirements
    requirements.sort()
  File "/home/erlingbo/.virtualenvs/mathjornet/lib/python3.4/site-packages/requirements_detector/requirement.py", line 101, in __gt__
    return self.name > other.name
TypeError: unorderable types: str() > NoneType()

```

**Comment by erlingbo** [comment] 2015-03-21 12:46
I see on the stack-trace that the bug probably is in requirements_detector

**Comment by erlingbo** [comment] 2015-03-21 13:09
Here is the content of ./requirements/
```
#requirements/base.txt
django==1.7.5
djangorestframework==3.0.5
django-filter==0.9.2
Markdown==2.5.2
django-cors-headers==1.0.0
python-social-auth==0.2.1
djangorestframework-jwt==1.2.0
djangorestframework-camel-case==0.2.0
------------
#requirements/dev.txt
-r base.txt
------------
#requirements/prod.txt
-r base.txt
http://www.lfd.uci.edu/~gohlke/pythonlibs/z94jfosk/pyodbc-3.0.7-cp34-none-win32.whl
django-pyodbc-azure
------------
```

**Comment by carlio** [comment] 2015-03-21 13:11
Thanks @erlingbo - this is already fixed in a PR on requirements-detector (see https://github.com/landscapeio/requirements-detector/pull/4) and I will make a new release soon including that fix (currently on holiday!)

**Comment by erlingbo** [comment] 2015-03-21 13:19
Great. I figured out that I could go round the problem by removing the pyodbc wheel from my prod requirements :)

**Comment by carlio** [comment] 2015-03-29 12:15
The upcoming 0.10 release of prospector will mandate `requirements-detector` 0.4 to include a fix for this.

**Closed by carlio** 2015-03-29 12:15 UTC
